# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: 			 false
markdown: 			 redcarpet
#relative_permalinks: true

# Setup
title:               R-338 (Renk) Takım Proje Sayfası
tagline:             'Akademik Bilişim 2016'
description:         'Kısa proje tanımını buraya girin'
url:                 http://r338.github.io/ab-2016
baseurl:             '/takim-taslak'
paginate:            5

# About/contact
author:
  name:              'Takım elemanları'
  url:               http://r338.github.io/takim-taslak
  email:             

# Custom vars
version:             1.0.0
