# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: 			 false
markdown: 			 redcarpet
#relative_permalinks: true

# Setup
title:               R ile Veri Analizi Kursu
tagline:             'Akademik Bilişim 2016'
description:         '30 Ocak - 2 Şubat 2016 tarihleri arasında düzenlenen Akademik Bilişim 2016 Kurslarından R ile Veri Analizi kursu web sayfası. Bu sayfadan eğitimle ilgili duyuru, ders materyalleri ve örnek kodlara ulaşabilirsiniz.'
url:                 http://r338.github.io/ab-2016
baseurl:             '/ab-2016'
paginate:            5

# About/contact
author:
  name:              'Mustafa Baydoğan & Berk Orbay'
  url:               http://r338.github.io/ab-2016
  email:             

# Custom vars
version:             1.0.0
